# A basic CI script to automate building / testing @ngx-dummy/accrordion-simple lib
name: CI

# Trigger on master, releases push / pull requests
on:
  push:
    branches:  
    - master
    - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 10, 13 ]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm    # npm cache files are stored in `~/.npm` on Linux
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install packages global
      run: |
        echo Installing..!
        npm install -g @angular/cli > /dev/null
    - name: Build accordion-sample app
      run: |
        echo Installing local packages and Building Sample app
        npm ci
        npm run build:sample --if-present
    - name: Copy to docs dir
      run: cp -r ./dist/accordion-sample/* ./docs/
      working-directory: ./
    - name: Make a drop
      uses: actions/upload-artifact@v1
      with:
        name: drop
        path: dist/accordion-sample
    - name: Run tests
      run: |
        echo Running tests
        npm run test:ci