# A basic CI script to automate publishing @ngx-dummy/accrordion-simple lib
name: GHPDEPLOY
# Trigger after release created 
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@ngx-dummy'
    - run: |
        echo Installing..!
        npm install -g @angular/cli > /dev/null
        npm ci
        npm run build:prod --if-present
    - run: npm run publish:full --if-present
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_PUBLISH_TOKEN }}