# A basic CI script to automate publishing @ngx-dummy/accrordion-simple lib
name: ghp-deploy
# Trigger after release created 
on:
  release:
    types: [created, published]
  push:
    # Sequence of patterns matched against refs/tags
    # Created when `npm run releae` commeand is executed (which pushes tagged commit with version pathed from current package.json version ..)
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v2.0.1

jobs:
  build:
    if: contains(github.repository_owner, 'ngx-dummy')
    runs-on: ubuntu-lates
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@ngx-dummy'
    - run: |
        echo Installing..!
        npm install -g @angular/cli > /dev/null
        npm ci
        npm run build:prod --if-present
    - run: npm run publish:full --if-present
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_PUBLISH_TOKEN }}