# A basic CI script to automate publishing @ngx-dummy/accrordion-simple lib

name: NPM-DEPLOY

# Trigger after release created (tagged version is pushed to repo)
on:
  release:
    types: [ created ]

jobs:
  build:
    if: contains('ngx-dummy', github.actor)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@ngx-dummy'
    - run: |
        echo Installing..!
        npm install -g @angular/cli > /dev/null
        npm ci
        npm run build:prod --if-present
    - run: npm run publish:full --if-present
      env: 
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}